spring:
    application:
        name: twitterapi
        author: Samuel Jesús Ordóñez Pareja

    datasource:
        url: jdbc:mysql://localhost:3306/apitwitter?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: validate

auth:
    access-token-secret-key: lMCvj7Sirkk41OpuXDBKoSA1YeQ4aTeHmP4gzoyoaLk=
    access-token-expiration: 180000
    refresh-token-secret-key: laCvj7Sirkk41OpuXDBKoSA1YeQ4aTeHmP4gzoyoaLk=
    refresh-token-expiration: 604800000  