spring:
    application:
        name: twitterapi
        author: Samuel Jesús Ordóñez Pareja

    datasource:
        url: jdbc:mysql://localhost:3306/apitwitter?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: validate